### ISSUE TITLE
URLにカスタムフィールド以外のクエリ文字がつくとエラーになる問題

### ISSUE THREAD

**Issue by katokaisya** [ecatchup/CuCustomField#17]
以前のインシデントでは、とりあえず応急処置として、customSearchQueryを使わない設定にもできるように調整して対応したが、基本設計の問題については解消していません。

CuCustomFieldDefinitionモデルから、keyのリストを取得し、それに含まれているかどうかの判定の追加が必要です。（ただし、判定のタイミングによって、ページネーションなどの影響が残る場合もある）

**Comment by MOMOGUSSAN** [comment]
上記の改修を適用させていただいたところ、本プラグインを使用していないブログも含めて、ブログ記事のプレビュー表示ができないエラーが出てしまいます。

**Comment by katokaisya** [comment]
@ MOMOGUSSAN
ご指摘ありがとうございます。

> 上記の改修を適用させていただいたところ、本プラグインを使用していないブログも含めて、ブログ記事のプレビュー表示ができないエラーが出てしまいます。

こちら、現象が再現できません。

おそらく、この改修の前の改修で、プレビューが表示できないエラーがあったので、そちらの問題では無いでしょうか？

**Comment by MOMOGUSSAN** [comment]
@katokaisya 
> おそらく、この改修の前の改修で、プレビューが表示できないエラーがあったので、そちらの問題では無いでしょうか？
すいません、「この改修の前の改修」というのは、具体的にどの改修でしょうか？
わかれば、確認してみます。

**Comment by katokaisya** [comment]
@MOMOGUSSAN 

https://github.com/ecatchup/CuCustomField/pull/15/commits/4ffd634acc51918e1d91f5bc5b31697984874e3e
等が該当します。
