### ISSUE TITLE
ブログ記事のプレビュー時にアイキャッチ画像が表示されない

### ISSUE THREAD

**Issue by materializing** [ecatchup/CuCustomField#27]
## 再現手順
- ブログ記事編集画面開き、アイキャッチ画像をファイル選択欄にセットする（※記事保存は行わない段階）
- 記事をプレビューする
    - アイキャッチ画像が表示されない

## 影響している箇所
- app/Plugin/CuCustomField/Plugin/CuCfFile/Model/Behavior/CuCfFileBehavior.php::saveTmpFile()内で、セッション内のUploadキーを全消ししていることで、セッション内に入っているアイキャッチ画像を消している
    - ```$this->Session->delete('Upload')```

**Comment by kaburk** [comment]
これ、ソースコード見ると、CuCustomFieldのファイル保存って、BcUploadBehavior使ってないのに、セッションキーがBcUploadBehaviorと同じにしていることが問題のようなので、セッションキー名を変えると問題解決かな、と思います。

**Comment by kaburk** [comment]
セッションキー名を変えると問題解決 -> だめでした、、、

コアのUploadsController 経由で /uploads/tmp/xxxxxx という感じで セッション内の画像を表示するので、セッションキーは変えられない感じでした。

削除するときにセッション内画像をすべて消さずに、該当ファイルだけ消す感じですかね、、、

**Comment by ryuring** [comment]
@kaburk @materializing 僕も後で確認してみますね

**Comment by materializing** [comment]
@ryuring @kaburk ご調整ありがとうございます
