### ISSUE TITLE
設定一覧画面と詳細画面で、項目名称が異なっているため揃える

### ISSUE THREAD

**Issue by fuchigam1** [ecatchup/CuCustomField#41]
- フィールド定義一覧画面での「フィールド名」が、編集画面では「フィールド定義名」になっている
- フィールド一覧画面での「フィールド定義名」が、編集画面では「入力欄ラベル」になっている

※追記
DZ河野さまからのフィードバック
https://e-catchup.slack.com/archives/C01AV12F52R/p1685691382808209

![sc_custom](https://github.com/ecatchup/CuCustomField/assets/1115768/cc900090-0f50-4c7e-afaa-a610560df49b)

**Comment by ryuring** [comment]
@fuchigam1 修正が可能でしたらお願いします。
