### ISSUE TITLE
ループを追加したあとは、JSによるチェックが効かない問題

### ISSUE THREAD

**Issue by katokaisya** [ecatchup/CuCustomField#8]
ループでフィールドを追加した場合、
チェックボックスやラジオボタンは、JSでチェックをつける仕様のため、追加されたラジオボタンやチェックボックスには、チェックがつかなくなります。
（一旦保存すればJSが再度読み込まれるため、チェックが効くようになります。）

**Comment by ryuring** [comment]
@katokaisya 
原因はわかりました。
やはりチェックボックスはCSSだけで処理されており、JSは使われていないです。

次のようなロジックになっていました。

ラベルをクリック
↓
隠れているチェックボックスにチェックが入る
↓
隠れているチェックボックスにチェックが入ったラベルの after が display:block になるようにCSSが書かれている

![スクリーンショット 2021-06-16 20 11 03](https://user-images.githubusercontent.com/90106/122209185-33fa4280-cedf-11eb-91c9-fd1c25c41d7e.png)

原因は、label の for と、隠れいているチェックボックスの id が違うことです。

![スクリーンショット 2021-06-16 20 08 22](https://user-images.githubusercontent.com/90106/122209285-512f1100-cedf-11eb-8cdd-831b07d323fa.png)

インスペクタで label の for を チェックボックスの id に強制的に合わせてあげると動作しました。

![スクリーンショット 2021-06-16 20 08 40](https://user-images.githubusercontent.com/90106/122209363-686dfe80-cedf-11eb-864e-d3993d9f4b61.png)

解決はできてませんが、 id と for を合わせる方針で対処しましょう。

**Comment by katokaisya** [comment]
@ryuring 
ご指導ありがとうございます。
プルリク送ってます。
